config/routes.rb
Rails.application.routes.draw do

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions, only: [:new, :destroy, :create]

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resource :user do
    resources :conversations, only: [:index, :show], controller: 'users/conversations'
    resources :schools, controller: 'users/schools' do
      resources :courses, controller: 'users/schools/courses' do
        resources :events, controller: 'users/schools/courses/events' do
          member do
            patch :toggle_attendance
          end
        end

      end
    end
  end

  root to: 'visitors#index'
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def self.r=(rr)
    @r = rr
  end

  def self.r
    @r
  end


  def index
    VisitorsController.r = Random.new(125)
    week = DateTime.now.beginning_of_week
    ungrouped_items = 40.times.map do |i|
      day = VisitorsController.r.rand(12).to_i
      s_time = VisitorsController.r.rand(265).to_i
      e_time = VisitorsController.r.rand([268 - s_time - 1, 60].min + 15).to_i + 1 + s_time
      opts = {
        title: Faker::Lorem.words(2).join(" ")
      }
      if s_time.even?
        opts[:class] = 'important'
      end
      {starts_at: week + day.days + (5* s_time).minutes,
       ends_at: week + day.days + (5*e_time).minutes,
       options: opts }
    end
    @calendar = Carendar::Calendar.new(DateTime.now.beginning_of_month, DateTime.now.end_of_month + 1.week, ungrouped_items)
  end
end

app/views/visitors/_dances.html.haml
%li
  = dance.name
  - if dance.children.any?
    %ul
      - dance.children.each do |child|
        = render partial: 'dances', locals: { dance: child }

app/views/visitors/index.html.haml
- if current_user
  %p Hi #{current_user.email}

  - if current_user.owned_schools.any?
    - current_user.owned_schools.each do |school|
      = owned_item_link(school)
      %br
  - else
    - current_user.events.each do |event|
      .row
        =l(event.starts_at)
        = event.name
- else
  = link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook)
  = link_to 'H18N login wiht PW', login_path
  %br
  = link_to "login as REne", user_sessions_path(login: {email: 'rene@example.org', password: '1qay2wsx'}), method: :post
  %br
  = link_to "login as Axel", user_sessions_path(login: {email: 'axel@example.org', password: '1qay2wsx'}), method: :post


-#%ul
  - Dance.tree.children.each do |dance|
    = render partial: 'dances', locals: { dance: dance }
-#= carendar(@calendar, class: 'school-calendar month') do |item|
  .title= item[:title]