config/routes.rb
Rails.application.routes.draw do

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions, only: [:new, :destroy, :create]

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resource :user do
    resources :conversations, only: [:index, :show], controller: 'users/conversations'
    resources :schools, controller: 'users/schools' do
      resources :courses, controller: 'users/schools/courses' do
        resources :events, controller: 'users/schools/courses/events' do
          member do
            patch :toggle_attendance
          end
        end

      end
    end
  end

  root to: 'visitors#index'
end

app/models/school.rb
class School < Institution
  def add_teachers!(teacher)
    teachers = Array.wrap(teacher)
    teachers.each do |t|
      Relationships::TeachesAt.create!(user: t, group: self)
    end
  end

  def courses
    Course.joins(:relationships)
      .where(relationships: {
        type: Relationships::CourseGivenBy.name,
        other_group: self})
  end

  def lessons(start_day = Date.today, end_day = (Time.now + 1.year).to_date)
    hosted_events_rel(start_day, end_day)
      .where('events.type = ?', Lesson.name)
      .map(&:event)
  end

  def teachers
    Relationships::TeachesAt
      .where(group: self)
  end

  def members
    User.joins(:relationships)
        .where(relationships: {
               type: Relationships::MemberAt,
               group: self})
  end

  def create_place(params)
    place = Place.create!(params)
    self.transaction do
      if place.save
        place.add_owners!(owners)
      end
    end
    place
  end

  def create_course(params, place)
    course = Course.new(params)
    course.end_day = DateTime.now.end_of_year
    course.transaction do
      course.generate_schedule
      if course.save
        course.add_host!(self)
        course.occurrences.each do |occurrence|
          lesson = Lesson.create!(group: course,
                        starts_at: occurrence.start_time,
                        ends_at: occurrence.start_time + course.duration.minutes,
                        place: place)
          lesson.add_host!(self)
        end
      end
    end
    course
  end
end

app/controllers/users/schools/courses/events_controller.rb
class Users::Schools::Courses::EventsController < ApplicationController
  before_filter :require_login
  before_action :load_school
  before_action :load_course
  before_action :load_event, only: [:show, :edit, :update, :toggle_attendance]

  def show
    @participants = @event.event_group.participants
    @attendees = @event.attendees
    @participants -= @attendees
  end

  def toggle_attendance
    user = User.find(params[:user_id])
    attendance = Relationships::Attended.find_by(group: @event, user: user)
    if attendance
      attendance.destroy
    else
      Relationships::Attended.create!(group: @event, user: user)
    end
    redirect_to action: :show
  end

  private

  def load_course
    @course = @school.courses.find { |course| course.id == params[:course_id] }
  end

  def schools
    current_user.owned_schools
  end

  def load_school
    @school = schools.find { |school| school.id == params[:school_id] }
  end

  def load_event
    @event = @course.events.find(params[:id])
  end
end

app/controllers/users/schools/courses_controller.rb
class Users::Schools::CoursesController < ApplicationController
  before_filter :require_login
  before_action :load_school
  before_action :load_course, only: [:show, :edit, :update]

  def index
    @courses = @school.courses
  end

  def show
    cal_start = Time.zone.now.beginning_of_month
    cal_end   = Time.zone.now.end_of_month
    events = @course.events.between(cal_start, cal_end)
    item_hashes = events.map do |event|
      {
        starts_at: event.starts_at,
        ends_at: event.ends_at,
        options: {title: event.event_group.name, event: event}
      }
    end
    @calendar = Carendar::Calendar.new(cal_start, cal_end, item_hashes)
  end

  def new
    @course = Course.new(starts_at: Time.now)
    @course.start_date = Date.today
    @course.schedule_rule = :none
  end

  def create
    @course = Course.new(course_params)
    @course.ends_at = DateTime.now.end_of_year
    @course.generate_schedule
    @course.transaction do
      if @course.save
        @course.add_owner!(current_user)
        @course.add_host!(@school)
        redirect_to user_school_course_path(@school, @course)
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to user_school_course_path(@course)
    else
      render :edit
    end
  end

  private

  def course_params
    p = params
        .require(:course)
        .permit(:name, :dances, :start_time, :duration, :start_date,
                :schedule_rule_weekly_interval,
                :schedule_rule_monthly_mode,
                :schedule_rule,
                { schedule_rule_monthly: [] },
                { schedule_rule_weekly: []}
               )
    p[:starts_at] = DateTime.strptime("#{p[:start_date]}##{p[:start_time]}", "%d.%m.%y#%k:%M")
    p
  end

  def load_course
    @course = @school.courses.find { |course| course.id == params[:id] }
  end

  def schools
    current_user.owned_schools
  end

  def load_school
    @school = schools.find { |school| school.id == params[:school_id] }
  end

end

app/controllers/users/schools_controller.rb
class Users::SchoolsController < ApplicationController
  before_filter :require_login
  before_action :load_school, only: [:show, :edit, :update]

  def index
    @schools = schools
  end

  def show
    cal_start = Time.zone.now.beginning_of_week
    cal_end   = Time.zone.now.end_of_week
    events = @school.hosted_events(cal_start, cal_end)
    item_hashes = events.map do |event|
      {
        starts_at: event.starts_at,
        ends_at: event.ends_at,
        options: {title: event.name, event: event}
      }
    end
    @calendar = Carendar::Calendar.new(cal_start, cal_end, item_hashes)

  end

  def new
    @school = School.new
  end

  def create
    School.transaction do
      @school = current_user.create_school(school_params)
      if @school.errors.any?
        redirect_to user_school_path(@school)
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    if @school.update(school_params)
      redirect_to user_school_path(@school)
    else
      render :edit
    end
  end

  private

  def school_params
    params.require(:school).permit(:name)
  end

  def schools
    current_user.owned_schools
  end

  def load_school
    @school = schools.find { |school| school.id == params[:id] }
  end

end

app/views/users/schools/courses/index.html.haml
%h1=@school.name

- @courses.each do |course|
  %p= link_to course.name, edit_user_school_course_path(course)

= link_to t('.new'), new_user_school_course_path

app/views/users/schools/courses/new.html.haml
= simple_form_for @course, url: user_school_courses_path, method: :post do |f|
  .row
    .columns.large-6
      = f.input :name
      = f.input :dances, collection: Dance.all, input_html: {'data-behaviour' => 'select2', style: 'width: 100%', multiple: true}
      .row
        .columns.large-6
          = f.input :start_time, as: :string
        .columns.large-6
          = f.input :duration, as: :integer
    .columns.large-6
      %h2 H18N Datum
      = f.input :start_date, as: :string
      = f.input :schedule_rule, as: :hidden
      %h3 H18N Wiederholung
      %ul.tabs{"data-tab" => ""}
        %li.tab-title.active
          %a{:href => "#no-recurr", onclick: '$("#course_schedule_rule").val("none")'} Keine
        %li.tab-title
          %a{:href => "#weekly-recurr", onclick: '$("#course_schedule_rule").val("weekly")'} Wöchentlich
        %li.tab-title
          %a{:href => "#monthly-recurr", onclick: '$("#course_schedule_rule").val("monthly")'} Monatlich
      .tabs-content
        #no-recurr.content.active
          %p H18N Der Termin findet einmalig statt
        #weekly-recurr.content
          = f.input :schedule_rule_weekly_interval, collection: (1..29).to_a
          .input
            - ((1..6).to_a + [0]).each do |day_index|
              - active = false #schedule_weekly_index_checked(tour_interval, day_index)
              = check_box_tag "course[schedule_rule_weekly][]"
              %label= I18n.t("date.abbr_day_names")[day_index]
        #monthly-recurr.content
          .repetition
            .rule_option.radio
              %label.choice
                = f.radio_button :schedule_rule_monthly_mode, "day_of_month"
                = t(".day_of_month", {day: @course.starts_at.day})
            -#.rule_option.radio
              %label.choice
                = f.radio_button :schedule_rule_monthly_mode, "day_of_month_reverse"
                = t(".day_of_month_reverse", {count: @course.starts_at.end_of_month.day - @course.starts_at.day + 1})
            .rule_option.radio
              %label.choice
                = f.radio_button :schedule_rule_monthly_mode, "weekday"
                = t(".weekday", {day: ((@course.starts_at.day - 1) / 7).to_i + 1, weekday: I18n.t("date.abbr_day_names")[@course.starts_at.wday]})
            -#.rule_option.radio
              %label.choice
                = f.radio_button :schedule_rule_monthly_mode, "weekday_reverse"
                = t(".weekday_reverse", {count: ((@course.starts_at.end_of_month.day - @course.starts_at.day) / 7).to_i + 1, weekday: I18n.t("date.abbr_day_names")[@course.starts_at.wday]})
          .months
            - (1..12).each do |month_index|
              = check_box_tag "course[schedule_rule_monthly][]", {id: "monthly#{month_index}"}, month_index
              %label{for: "monthly#{month_index}"}= I18n.t("date.abbr_month_names")[month_index]
  .row
    = f.button :submit

app/views/users/schools/courses/show.html.haml
%ul.breadcrumbs
  %li
    = owned_item_link(@school)
  %li.current
    = owned_item_link(@course)
%h1= @course.name

.row
  .columns.large-8(style="border: 1px solid red")
    = carendar @calendar, class: 'school-calendar month' do |event|
      .title
        = owned_item_link(event[:event])
  .columns.large-4(style="border: 1px solid red")
    %h2 H18N Trainer
    %ul
      - @course.teachers.each do |teacher|
        %li= teacher.display_name
    %h2 H18N Kursteilnehmer
    %ul
      - @course.participants.each do |participant|
        %li= participant.display_name