config/routes.rb
Rails.application.routes.draw do

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :user_sessions, only: [:new, :destroy, :create]

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resource :user do
    resources :conversations, only: [:index, :show], controller: 'users/conversations'
    resources :schools, controller: 'users/schools' do
      resources :courses, controller: 'users/schools/courses' do
        resources :events, controller: 'users/schools/courses/events' do
          member do
            patch :toggle_attendance
          end
        end

      end
    end
  end

  root to: 'visitors#index'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name
      %h1
        %a{:href => root_path} I dance a lot
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Right Nav Section
    %ul.right
      -#%li.active
        %a{:href => "#"} Right Button Active
      %li

      - if current_user
        %li.has-dropdown
          %a{:href => "#"}= current_user.email
          %ul.dropdown
            %li
              =link_to t('H18N ICH'), user_path
            %li
              =link_to t('global.conversations'), user_conversations_path
            %li.active
              = link_to t('global.logout'), logout_path, method: :post
    / Left Nav Section
    %ul.left
      %li

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Sirdancealot'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Sirdancealot'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield